nextcloud:
  url: ${NEXTCLOUD_URL}
  username: ${NEXTCLOUD_USERNAME}
  password: ${NEXTCLOUD_PASSWORD}

phones:
  - name: ${PHONE1_NAME}
    patch: ${PHONE1_PATCH}
  - name: ${PHONE2_NAME}
    patch: ${PHONE2_PATCH}
  